$ANSIBLE_VAULT;1.1;AES256
66656639646463646262393562366565633730363933313239303765623135333765623738373231
3861363866356530656366326537653231643934313733370a633065646132663162333965323863
37333731313636323130653865373366643632396562356231656661396264643761343638353465
3663373131393964650a393962613031623639336536663831323763623261656232366466386330
38313432653138383732616433316435613037626532343839626564643631386264333465356637
63613231646436636566613336316634306636643662333238623863303062386439393735336333
34313937313766323334656462366438666336636365343035373933316562626465383033623139
35633933623937343963323864633261663232656134313038366338626231303963393231336333
36303263363462313638333731616563643363643562316130623735343434623731363836623036
3038333736373133653164646336336635363265623931626265
